patch out some cpu feature stuff that was causing trouble
- x86Intrin.h is just the wrong casing I think, lowercase exists but uppercase does not
- Was hitting `rufus/src/cpu.c:113:80: error: invalid cpu feature string for builtin` when detecting "sha" for some unknown reason
  + Note: This reproduces in vanilla clang with any call to `__builtin_cpu_supports("sha")`, so this `#if` branch likely just doesn't work for clang at all